### ISSUE TITLE
Issue con Catapulta (?)

### ISSUE THREAD

**Issue by diegosanchez** [hhuzan/AlgoIII-TP2#9]
Les comparto la captura que evidencia el error. Tengo entendido que este ataque debería llevarse a cabo.

![CatapultaAtacaInfanteria](https://user-images.githubusercontent.com/3934479/70381467-96fe3700-1942-11ea-9a87-7f78da63ef6c.png)

**Comment by Savantage** [comment]
Hola, @diegosanchez , la distancia a la que debe estar una unidad respecto a la catapulta debe ser mayor a 5 unidades. En este caso, el soldado turquesa señalado se encuentra a 4 unidades de la catapulta, por lo que no está en su rango.
_________________________________
![Rango Cercano](https://user-images.githubusercontent.com/38823584/70381839-47af0b00-1930-11ea-9140-b23c3fe1ed17.png)
_________________________________
![Rango Mediano](https://user-images.githubusercontent.com/38823584/70381842-4da4ec00-1930-11ea-83d6-ce61c9db469a.png)
_________________________________
![Rango Lejano](https://user-images.githubusercontent.com/38823584/70381843-50074600-1930-11ea-9ec5-288c0a9992a0.png)
